# Generated by Django 5.2.5 on 2025-08-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_users_actived_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='googleauth',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='users',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='users',
            name='telegram_user_id',
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Security Analyst'), ('user', 'User')], default='user', max_length=50),
        ),
        migrations.AlterModelTable(
            name='githubauth',
            table=None,
        ),
        migrations.AlterModelTable(
            name='googleauth',
            table=None,
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
