# Generated by Django 5.2.5 on 2025-09-01 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 1, 8, 59, 57, 390332, tzinfo=datetime.timezone.utc)),
        ),
    ]
